[package]
name = "card_view"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
flexi_logger = "0.28.0"
iced = { git = "https://github.com/iced-rs/iced.git" }
log = "0.4.21"
